version: "3.7"
services:
  eagle_app:
    build:
      context: ../eagle_app
      dockerfile: ../eagle-client-docker/dockerfiles/Dockerfile-eagle_app
    ports:
      - "3000:3000"
    working_dir: /app
    command: yarn start -p 3000

  eagle_api_gateway:
    build:
      context: ../eagle_api_gateway
      dockerfile: ../eagle-client-docker/dockerfiles/Dockerfile-eagle_api_gateway
    ports:
      - "3001:3001"
    working_dir: /app
    command: yarn start -p 3001
    environment:
      - WORKFLOW_API=eagle_workflow_api