FROM node:10.13

RUN mkdir -p /app
WORKDIR /app

COPY . /app

RUN apt-get update
RUN apt-get install apt-transport-https

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update
RUN apt-get install -y yarn \
  libsasl2-dev

RUN yarn install

EXPOSE 3001

CMD ["yarn dev -p 3001"]