FROM node:10.13

RUN mkdir -p /app
WORKDIR /app

COPY . /app

RUN apt-get update
RUN apt-get install apt-transport-https

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update
RUN apt-get install yarn -y

RUN yarn install

EXPOSE 3000

CMD ["yarn start -p 3000"]